spring.application.name=admin-server

# ==================================
# (MariaDB)
# ==================================
# DB
spring.datasource.url=jdbc:mariadb://localhost:3306/ai_matchex

# DB ?? ?? ??: root ??
spring.datasource.username=root
spring.datasource.password=1642
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==================================
# JPA
# ==================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ==================================
# JWT
# ==================================
jwt.secret = U3VwZXItU2VjcmV0LUZvci1PVVItQVdFU09NRS1Qcm9qZWN0LTIwMjU=

# 1. ?? ??? ?? URL
ai.fastapi.url.scorer=http://localhost:8091/admin/ai-model-scorer
ai.fastapi.url.acceptor=http://localhost:8091/admin/ai-model-acceptor
ai.fastapi.url.embedding=http://localhost:8091/admin/ai-model-embedding

# 2. '??? ??' ???? ?? URL
ai.fastapi.url.parameter.score=http://localhost:8091/model/parameter/score

# 3. '???? ??' ???? ?? URL
ai.fastapi.url.parameter.acceptor=http://localhost:8091/model/parameter/acceptor

# ==================================
# ???? ?? ?? ??
# ==================================

# Spring Security? ?? ?? ON - ?? ?? ?? ???
logging.level.org.springframework.security=DEBUG

# ? ?? ?? ??(DispatcherServlet ?)? ?? ?? ON
logging.level.org.springframework.web=DEBUG

# Hibernate(DB) ?? ?????? ?? ???
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE