# application-prod.properties (?? ??? ??)

# ?? ?? ??
server.port=60002

# ==================================
# (MariaDB) ?? ??
# ==================================
# ?? ?? DB ??
spring.datasource.url=jdbc:mariadb://localhost:3306/db25202
spring.datasource.username=dbid252
spring.datasource.password=dbpass252
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==================================
# JPA ??
# ==================================
# 'validate'? ????, ??? DB ???? ???? ?? ??, update ?? ?? ??!!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ==================================
# JWT ?? ?
# ==================================
jwt.secret=U3VwZXItU2VjcmV0LUZvci1PVVItQVdFU09NRS1Qcm9qZWN0LTIwMjU=

# ==================================
# AI (FastAPI) ?? ?? ?? (?? ??)
# ==================================

# 1. ?? ??? ?? URL
ai.fastapi.url.scorer=http://localhost:8091/admin/ai-model-scorer
ai.fastapi.url.acceptor=http://localhost:8091/admin/ai-model-acceptor
ai.fastapi.url.embedding=http://localhost:8091/admin/ai-model-embedding

# 2. '??? ??' ???? ?? URL
ai.fastapi.url.parameter.score=http://localhost:8091/model/parameter/score

# 3. '???? ??' ???? ?? URL
ai.fastapi.url.parameter.acceptor=http://localhost:8091/model/parameter/acceptor